name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false # 避免使用默认 token
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install || echo "No package.json found, skipping install"
      
    - name: Build project
      run: npm run build || echo "No build script found, using static files"
      
    - name: Create deployment directory
      run: |
        mkdir -p ./deploy
        cp -r css data js index.html ./deploy/
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ./deploy # 部署目录
        branch: gh-pages # 部署分支
        token: ${{ secrets.GITHUB_TOKEN }}
        clean: true # 清理旧文件